# Generated by Django 3.2.18 on 2026-06-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0022_auto_20251203_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='epolyscat_django_app.experiment'),
        ),
        migrations.AlterField(
            model_name='run',
            name='filepath',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='run',
            name='number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='run',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='epolyscat_django_app.runsroot'),
        ),
    ]
