# Generated by Django 3.2.18 on 2026-06-17 21:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epolyscat_django_app', '0023_auto_20260617_1802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('name', 'owner')},
        ),
    ]
